### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Limitbreak7777** [xtangle/zoundcloud#17]
(sorry, don't know anything about programming or GitHub, got registered for the sole purpose of sending feedback for this extension. thanks for the great work on it!)

Here's the song I was trying to download:

https://soundcloud.com/tycho/maggie-rogers-alaska-tycho-remix-1?in=nickraymondg/sets/weekly-chill-volume-18

from the playlist:

https://soundcloud.com/nickraymondg/sets/weekly-chill-volume-18

Chrome version is:
Google Chrome is up to date
Version 72.0.3626.96 (Official Build) (64-bit)

After clicking on the button, nothing happens. I've tried cleaning cache, rebooting PC, reinstalling plug-in, downloading from a separate window. 

Please let me know what other info I should provide. Thanks!

**Comment by xtangle** [comment]
Glad you liked the extension and I appreciate you signing up for GitHub just to post the issue. I was able to reproduce the problem on my browser and it's weird that it only occurs for some songs and not others. Anyways I found the fix and it should be patched in the next release :)
