### ISSUE TITLE
add 320 kbps

### ISSUE THREAD

**Issue by jcvr1994** [xtangle/zoundcloud#22]
add 320 kbps soundcloud downloader

**Comment by xtangle** [comment]
As far as I'm aware, Soundcloud does not provide a 320 kbps stream for tracks that the artist didn't put a download link for. The extension has logic already in it to check if a higher quality version mp3 is available, and will automatically choose a higher quality mp3 over a lower quality one.

Consider unchecking 'Always download tracks in .mp3 format' in the options page. This allows the extension to download tracks that are uploaded in other formats if they are available.

**Comment by rpavantica** [comment]
There is a Soundcloud GO+ $10/m that allows you to stream at 320kbs. If the artist used that bitrate during the upload.
